//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products
    {
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Size { get; set; }
        public int Price { get; set; }
        public System.DateTime MfgDate { get; set; }
        public string Category { get; set; }
    }
}
